name: FitIsland CI/CD

# main 브랜치가 push 되면 실행
on:
  push:
    branches:
      - main

jobs:
  # job1 - jar 빌드
  build:
    runs-on: ubuntu-latest
    steps:
      # 코드 체크아웃
      - uses: actions/checkout@v4

      # JDK 21 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      #--- .gitignore 에 의해 .jar 파일이 없기 때문에 Gradle 설정 ---#
      # Gradle 설치
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      # Gradle Wrapper 생성
      - name: Generate Gradle Wrapper
        run: gradle wrapper
      #--- end ---#

      #환경변수 추가
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > src/main/resources/.env

      # Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew build

      # 빌드 결과 확인 - 필수 X
      - name: Check build output
        run: ls -al build/libs

      # Docker 컨텍스트에서 JAR 파일 확인 - 필수 X
      - name: Verify JAR file in context
        run: ls -al

      # job 간 이동을 위해서 jar 파일 업로드
      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: build/libs/*SNAPSHOT.jar

  # job2 - NCP container registry 에 이미지 파일 push
  push_to_registry:
    name: Push to NCP Container Registry
    runs-on: ubuntu-latest
    needs: build # build 가 끝나고 실행
    steps:
      # 코드 체크아웃
      - uses: actions/checkout@v4

      # jar 다운로드
      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: app-jar
          path: .

      # 빌드 결과 확인 - 필수 X
      - name: Check build output
        run: ls -al

      # Docker Buildx 설정 -> 빌드 환경 차이로 발생하는 에러문제 해결
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # NCP Container Registry 로그인
      - name: Login to NCP Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NCP_CONTAINER_REGISTRY }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

      # Docker 이미지 빌드 및 푸시
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.NCP_CONTAINER_REGISTRY }}/fitisland:latest

  # job3 - NCP에서 이미지를 가져와서 실행
  pull_from_registry:
    name: Connect server ssh and pull from container registry
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
      - name: Connect via SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.DEV_USERNAME }}
          password: ${{ secrets.DEV_PASSWORD }}
          port: ${{ secrets.DEV_PORT }}
          # 순서대로 설명
          # 도커 이미지 ncp_container_registry pull
          # 기존 도커 컨테이너 stop
          # docker 컨테이너 삭제
          # docker run -d(백그라운드) -p(포트연결) 8080(호스트서버포트):8080(컨테이너포트)
          # 사용하지 않는 도커 이미지 삭제
          script: |
            docker pull ${{ secrets.NCP_CONTAINER_REGISTRY }}/fitisland
            # 기존 컨테이너 중지
            docker stop $(docker ps -aq --filter "name=fitisland-app") || true
            # 컨테이너 제거
            docker rm $(docker ps -aq --filter "name=fitisland-app") || true
            # 새 컨테이너 실행 (이름 고정)
            docker run -d -p 8080:8080 --name fitisland-app ${{ secrets.NCP_CONTAINER_REGISTRY }}/fitisland
            docker image prune -fa
